### ISSUE TITLE
question: in napari Python console, how can I (programmatically) stream the newly acquired images to the viewer?

### ISSUE THREAD

**Issue by linshaova** [pymmcore-plus/napari-micromanager#305]
Hello,

After launching napari-MM and verifying that MM configuration and camera etc. worked, I opened its Python console and obtained a reference `mmc` to the same core object using the `CMMCorePlus.instance` call (verified with `mmc.getFocusDevice` for example). However, when I then ran `mmc.snapImage` or `mmc.run_mda`, I didn't see the default image viewer updating with the newly acquired images. What other steps are needed? Thanks!

-lin

**Comment by tlambert03** [comment]
- `mmc.snapImage`

This one doesn't immediately show anything is because (perhaps surprisingly) it doesn't emit any event that napari is listening to;  `mmc.snap()` will however (it's a combination of `snapImage()` and `getImage()`, added in pymmcore-plus)
this confusion is also discussed in: https://github.com/pymmcore-plus/pymmcore-plus/issues/144

- `mmc.run_mda`

This one doesn't work at the moment because, currently, napari-micromanager only pays attention to MDAs that it started itself.  This is a bit of an arbitrary decision, and probably overly "cautious". 

It's caused by this line right here:

https://github.com/pymmcore-plus/napari-micromanager/blob/ebddc0aee75d85011ac07ff3365d513c9abd28e4/src/napari_micromanager/_mda_handler.py#L194C1-L196C30

it would be *very* easy to change that behavior.  If you want to "hack" it to just work for you, all you need to do is add a little metadata to the MDASequence:

```python
from useq import MDASequence
from napari_micromanager._mda_meta import SequenceMeta

fake_meta = {'napari_mm_sequence_meta': SequenceMeta()}
core.run_mda(MDASequence(time_plan={'loops': 5, 'interval': 0.1}, metadata= fake_meta))
```

what do we think, lin and @fdrgsp, should napari-micromanager just show *all* running mdas? regardless of how they were started?

**Comment by tlambert03** [comment]
I edited the title here to say "programmatically"... note that if you hit the snap or live buttons:

<img width="80" alt="image" src="https://github.com/pymmcore-plus/napari-micromanager/assets/1609449/08567e02-59d9-42f6-9543-46700015796d">


or press the MDA button to open the MDA widget: 
<img width="45" alt="image" src="https://github.com/pymmcore-plus/napari-micromanager/assets/1609449/1c719b3d-818e-490f-bd9f-fd2cee8a31d4">
and then run an MDA with 
<img width="90" alt="image" src="https://github.com/pymmcore-plus/napari-micromanager/assets/1609449/3bcead04-1ed6-44c3-98d1-273357bc97b1">

it will populate the viewer with the images

**Comment by linshaova** [comment]
Thank you! The suggested hack kind of works. I had to call the `fake_meta = ...` line every time before `run_mda(...)` though for the viewer to update with incoming images. If I `run_mda(...)` consecutively, the viewer's z slide moves, but the display remains black.

I vote for napari showing all MDAs regardless of the origin.
